default_language_version:
  python: python3.10

repos:
  # black - code formatter
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  # flake8 - style guide enforcement
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  # isort - import organizer
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  # mypy
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.991
  #   hooks:
  #     - id: mypy
  #       args:
  #         [
  #           "--config-file",
  #           "setup.cfg",
  #           "--no-strict-optional",
  #           "--ignore-missing-imports",
  #         ]

  # gitlint - git commit message linter
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  # poetry (has bugs in 1.4.0, --directory not working for poetry-check & poetry-export)
  - repo: https://github.com/python-poetry/poetry
    rev: "1.5.1"
    hooks:
      - id: poetry-check
        language_version: python3.10
        args: ["--directory", "app"]
      - id: poetry-lock
        language_version: python3.10
        args: ["--directory", "app"]
      - id: poetry-export
        language_version: python3.10
        args:
          [
            "--directory",
            "app",
            "-f",
            "requirements.txt",
            "-o",
            "requirements.txt",
          ]
