apiVersion: v1
kind: Namespace
metadata:
  name: getdeck

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: getdeck
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-api-svc
  selector:
    app: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: getdeck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: quay.io/getdeck/api:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: settings
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
          ports:
            - name: http-api-svc
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
      serviceAccountName: api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: getdeck

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: getdeck:api
rules:
  - apiGroups:
      - "getdeck.dev"
    resources:
      - beiboots
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: getdeck-api
  namespace: getdeck
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: getdeck:api
subjects:
  - kind: ServiceAccount
    name: api
    namespace: getdeck
