apiVersion: v1
kind: Namespace
metadata:
  name: getdeck

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beiboot-api-config
  namespace: getdeck
data:
  clusterLifetimeLimit: "1h"

---
apiVersion: v1
kind: Service
metadata:
  name: beiboot-api
  namespace: getdeck
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-bbt-svc
  selector:
    app: beiboot-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beiboot-api
  name: beiboot-api
  namespace: getdeck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beiboot-api
  template:
    metadata:
      labels:
        app: beiboot-api
    spec:
      containers:
        - name: beiboot-api
          image: quay.io/getdeck/beiboot-api:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: beiboot-settings-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
          ports:
            - name: http-bbt-svc
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
      serviceAccountName: beiboot-api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beiboot-api
  namespace: getdeck

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: getdeck:beiboot:api
rules:
  - apiGroups:
      - "getdeck.dev"
    resources:
      - beiboots
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: getdeck-beiboot-api
  namespace: getdeck
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: getdeck:beiboot:api
subjects:
  - kind: ServiceAccount
    name: beiboot-api
    namespace: getdeck
