[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Christian Busch <christian@blueshoe.io>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.88.0"
uvicorn = "^0.20.0"
pydantic = "^1.10.2"
sentry-sdk = {extras = ["fastapi"], version = "^1.11.1"}
kubernetes = "<24.0.0"
beiboot = "1.1.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
flake8 = "^6.0.0"
pytest = "^7.2.0"
coverage = "^6.5.0"
pytest-timeout = "^2.1.0"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
