name: Code Style

on:
  workflow_call: {}

jobs:
  code-style:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: app/
        run: |
          pip install --upgrade pip poetry
          poetry install --no-interaction --no-ansi

      - name: Lint with flake8
        working-directory: app/
        run: |
          poetry run flake8 . --exit-zero

      - name: Lint with black
        working-directory: app/
        run: |
          poetry run black --check .
