name: WIP

on:
  push:
    branches: [typescript-client]
  workflow_dispatch: {}

jobs:
  bump-ts-client:
    runs-on: ubuntu-latest
    # needs: publish-docker-image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Get OpenAPI Schema
        working-directory: ./clients/typescript
        run: docker run --user 0 quay.io/getdeck/beiboot-rest:latest bash -c "python get_openapi.py && cat openapi.json" > openapi.json && ls
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate and Build
        working-directory: ./clients/typescript
        run: |
          ls
          npm ci
          npm run generate-client
          npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./clients/typescript/package.json
          token: ${{ secrets.NPM_TOKEN }}
